-- AlterTable
ALTER TABLE `delivery` MODIFY `status` ENUM('PENDING', 'IN_TRANSIT', 'DELIVERED', 'CANCELED', 'DELAYED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PENDING', 'COMPLETED', 'DEPOSITED', 'CANCELLED', 'REFUNDED', 'CREDIT_USED') NOT NULL DEFAULT 'PENDING';
