CREATE TABLE
    IF NOT EXISTS users (
        id BIGINT NOT NULL AUTO_INCREMENT,
        username VARCHAR(255) NOT NULL,
        name VARCHAR(100) NOT NULL,
        image VARCHAR(100),
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT user_pk PRIMARY KEY (id)
    );